### ISSUE TITLE
Proposal to adopt Conventional Commits at the project

### ISSUE THREAD

**Issue by gabrielzschmitz** [PQC-Group-UTFPR/avacpq#10]
**Description:**
I propose that the Avacpq project adopts the Conventional Commits commit message format for better organization and readability of commit history. Conventional Commits follow a structured format that includes a header, body, and footer, providing clear and concise information about each commit.

**Benefits:**
- Consistency: enforcing a standardized commit message format ensures consistency across the project, making it easier for contributors to understand and follow.
- Clarity: the Conventional Commits format provides clear and informative commit messages, which can aid in understanding the purpose and context of each change.
- Semantic Versioning: by following a structured format, it becomes easier to automate versioning and release notes generation based on commit messages.
- Improved Collaboration: clear commit messages facilitate better collaboration among team members and make it easier to track changes over time.

**Proposal:**
- Adopt Conventional Commits: start using the Conventional Commits format for all commits in the Avacpq project.
- Create Contribution Guidelines: create a project contribution guidelines to reflect the new commit message format and provide examples and guidelines for writing commit messages.
- Educate Contributors: inform contributors about the new commit message format and its importance for maintaining a clean and organized commit history.
- Enforce Guidelines: encourage contributors to adhere to the commit message format by enforcing guidelines during code reviews.

**Additional resources:**
* [Official website](https://www.conventionalcommits.org), official conventional commits website
* [Community Reference Sheet](https://gist.github.com/brianclements/841ea7bffdb01346392c), a quick and dirty reference sheet maintained by the community

**Comment by PQC-Group-UTFPR** [comment]
Great suggestion! Let's discuss it in the next meeting.
